### ISSUE TITLE
Cliente angular 

### ISSUE THREAD

**Issue by mspasiuk** [hexacta/iMe#4]
Cliente angular basico.
Que les parece este generador?
http://fountainjs.io/doc/usage/

**Comment by mauripardo** [comment]
Comparalo con ng-poly , este ultimo sigue las best practices de J Pappa y
Tod mot

**Comment by mspasiuk** [comment]
Genial, lo tengo en cuenta

**Comment by mspasiuk** [comment]
PR #7
