### ISSUE TITLE
Refactor de GetPersonalInfo en PersonalInfoService

### ISSUE THREAD

**Issue by mspasiuk** [hexacta/iMe#9]
Cambiar ese foreach por un diccionario para resolver la delegación de las llamadas a los servicios de twitter y github
Ver comentario de @mauripardo  en PR #8

**Comment by lggomez** [comment]
Por ahora son los siguientes items

- [x] Mejorar la resolución de clases
- [x] Mejorar el registro de las mismas si se puede

**Comment by lggomez** [comment]
Ya esta pusheado el refactor en 57a298402419338a4fbab18b11ed58e08524bf6a y 14e716d3180a131da27808e3883831a3f42386db

De ser necesarios refactors adicionales deberia abrirse otro issue
